grade1=input("Enter the grade of first student:")
grade2=input("Enter the grade of second student:")
grade3=input("Enter the grade of third student:")
grade4=input("Enter the grade of fourth student:")
grade5=input("Enter the grade of fifth student:")
grade6=input("Enter the grade of sixth student:")
list=[grade1,grade2,grade3,grade4,grade5,grade6]
print("The count of 'A' grade is")
count=list.count("A")
print(count)